### ISSUE TITLE
文件夹在重新命名后未考虑到原本的文件夹问题

### ISSUE THREAD

**Issue by welann** [Antonoko/Windrecorder#22]
在重命名 `catch -> cache` 的时候，忘记增加一个把原本的`catch`文件夹重命名为`cache`的逻辑了，所以会出现报错
更改文件名之后可以正常运行
`[Errno 2] No such file or directory: 'cache\\LAST_IDLE_MAINTAIN.MD'`

```
Starting Recording Screen...
No conda env active, defaulting to base
Traceback (most recent call last):
  File "D:\Windrecorder\recordScreen.py", line 38, in <module>
    with open(config.last_idle_maintain_file_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache\\LAST_IDLE_MAINTAIN.MD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Windrecorder\recordScreen.py", line 42, in <module>
    with open(config.last_idle_maintain_file_path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache\\LAST_IDLE_MAINTAIN.MD'
```

**Comment by welann** [comment]
#15

**Comment by welann** [comment]
又看了一下代码，有一个 `check_and_create_folder`，那么是其他地方有依赖关系没处理好么？导致去寻找一个不存在的文件
