### ISSUE TITLE
安装时候报错

### ISSUE THREAD

**Issue by srnabab** [Antonoko/Windrecorder#27]
files: folder existed:./db
dbManager: Initialize the database...
Traceback (most recent call last):
  File "C:\D\windrecorder\Windrecorder\onboard_setting.py", line 6, in <module>
    import windrecorder.maintainManager as maintainManager
  File "C:\D\windrecorder\Windrecorder\windrecorder\maintainManager.py", line 14, in <module>
    import windrecorder.db_manager as db_manager
  File "C:\D\windrecorder\Windrecorder\windrecorder\db_manager.py", line 34, in <module>
    db_main_initialize()
  File "C:\D\windrecorder\Windrecorder\windrecorder\db_manager.py", line 27, in db_main_initialize
    conn_check = db_check_exist(db_filepath_today)
NameError: name 'db_check_exist' is not defined

**Comment by Antonoko** [comment]
感谢反馈！已经修复啦，请在目录底下命令行 git pull 更新再试试！
