### ISSUE TITLE
记忆摘要部分中的词云和光箱无法正确更新

### ISSUE THREAD

**Issue by welann** [Antonoko/Windrecorder#31]
```
Traceback (most recent call last):
  File "D:\Windrecorder\env\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "D:\Windrecorder\webui.py", line 94, in <module>
    windrecorder.ui.state.render()
  File "D:\Windrecorder\windrecorder\ui\state.py", line 102, in render
    state.generate_month_lightbox(
  File "D:\Windrecorder\windrecorder\state.py", line 131, in generate_month_lightbox
    image_thumbnail = Image.open(BytesIO(base64.b64decode(image_data)))
  File "C:\Users\xxx\scoop\apps\miniconda3\current\lib\base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "C:\Users\xxx\scoop\apps\miniconda3\current\lib\base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```

其中，`state.py` 的 `image_list` 类型是 `list` ，而 `image_list[0]` 的类型是 `NoneType` 

不太懂py开发，这应该是代码间传输数据类型的问题吧？

**Comment by Antonoko** [comment]
感谢反馈，问题已修复！当创建新的数据库时，第一行数据中第一张预览图为空，此时不做跳过处理将导致生成阻塞。
